
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DECIMAL DIV ENTERO IGUAL LLAA LLAC RDIVISION RMULTIPLICACION RNUMERO ROPERACION RRESTA RSUMA RTIPOinit : instruccionesinstrucciones    : instrucciones instruccion\n                        |   instruccioninstruccion  : LLAA RTIPO LLAC instrucciones_2 LLAA DIV RTIPO LLACinstrucciones_2 : instrucciones_2 instruccion_2instrucciones_2 :  instruccion_2instruccion_2  :  LLAA ROPERACION IGUAL tipo LLAC instrucciones_2 LLAA DIV ROPERACION LLACinstruccion_2 : LLAA RNUMERO LLAC DECIMAL LLAA DIV RNUMERO LLAC instruccion_2 : LLAA RNUMERO LLAC ENTERO LLAA DIV RNUMERO LLAC tipo :   RSUMA\n            |   RRESTA\n            |   RMULTIPLICACION\n            |   RDIVISION\n    '
    
_lr_action_items = {'LLAA':([0,2,3,5,7,9,10,14,23,24,26,29,30,37,38,40,],[4,4,-3,-2,8,13,-6,-5,27,28,8,-4,33,-8,-9,-7,]),'$end':([1,2,3,5,29,],[0,-1,-3,-2,-4,]),'RTIPO':([4,17,],[6,25,]),'LLAC':([6,12,18,19,20,21,22,25,34,35,39,],[7,16,26,-10,-11,-12,-13,29,37,38,40,]),'ROPERACION':([8,13,33,36,],[11,11,11,39,]),'RNUMERO':([8,13,31,32,33,],[12,12,34,35,12,]),'IGUAL':([11,],[15,]),'DIV':([13,27,28,33,],[17,31,32,36,]),'RSUMA':([15,],[19,]),'RRESTA':([15,],[20,]),'RMULTIPLICACION':([15,],[21,]),'RDIVISION':([15,],[22,]),'DECIMAL':([16,],[23,]),'ENTERO':([16,],[24,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'init':([0,],[1,]),'instrucciones':([0,],[2,]),'instruccion':([0,2,],[3,5,]),'instrucciones_2':([7,26,],[9,30,]),'instruccion_2':([7,9,26,30,],[10,14,10,14,]),'tipo':([15,],[18,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> init","S'",1,None,None,None),
  ('init -> instrucciones','init',1,'p_init','analizador_lexico.py',93),
  ('instrucciones -> instrucciones instruccion','instrucciones',2,'p_instrucciones_lista','analizador_lexico.py',98),
  ('instrucciones -> instruccion','instrucciones',1,'p_instrucciones_lista','analizador_lexico.py',99),
  ('instruccion -> LLAA RTIPO LLAC instrucciones_2 LLAA DIV RTIPO LLAC','instruccion',8,'p_instruccion','analizador_lexico.py',107),
  ('instrucciones_2 -> instrucciones_2 instruccion_2','instrucciones_2',2,'p_instrucciones_2_lista','analizador_lexico.py',111),
  ('instrucciones_2 -> instruccion_2','instrucciones_2',1,'p_instrucciones_2_instruccion','analizador_lexico.py',116),
  ('instruccion_2 -> LLAA ROPERACION IGUAL tipo LLAC instrucciones_2 LLAA DIV ROPERACION LLAC','instruccion_2',10,'p_instruccion_2','analizador_lexico.py',120),
  ('instruccion_2 -> LLAA RNUMERO LLAC DECIMAL LLAA DIV RNUMERO LLAC','instruccion_2',8,'p_instruccion_2_decimal','analizador_lexico.py',124),
  ('instruccion_2 -> LLAA RNUMERO LLAC ENTERO LLAA DIV RNUMERO LLAC','instruccion_2',8,'p_instruccion_2_entero','analizador_lexico.py',128),
  ('tipo -> RSUMA','tipo',1,'p_tipo','analizador_lexico.py',139),
  ('tipo -> RRESTA','tipo',1,'p_tipo','analizador_lexico.py',140),
  ('tipo -> RMULTIPLICACION','tipo',1,'p_tipo','analizador_lexico.py',141),
  ('tipo -> RDIVISION','tipo',1,'p_tipo','analizador_lexico.py',142),
]
